/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Data.EquipoData;
import Data.ProyectoData;
import Entidad.Equipo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonardo
 */
public class ViewBuscarProyectoPorID extends javax.swing.JInternalFrame {

    private EquipoData ed = new EquipoData();
    private ProyectoData pd = new ProyectoData();
    private DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form ViewBuscarProyectoPorID
     */
    public ViewBuscarProyectoPorID() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jrTareas = new javax.swing.JRadioButton();
        jrProyectos = new javax.swing.JRadioButton();
        jrEquipos = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProyecto = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();

        jrTareas.setText("Tareas");

        jrProyectos.setText("Proyectos");

        jrEquipos.setText("Equipos");
        jrEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrEquiposActionPerformed(evt);
            }
        });

        jtProyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtProyecto);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jrEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrTareas)
                        .addGap(18, 18, 18)
                        .addComponent(jrProyectos)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrEquipos)
                    .addComponent(jrTareas)
                    .addComponent(jrProyectos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jrEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrEquiposActionPerformed
        armarCabecera();
        List<Equipo> equipo = ed.traerTodosActivos();

    }//GEN-LAST:event_jrEquiposActionPerformed
    private void armarCabecera() {
        ArrayList equipos = new ArrayList();
        equipos.add("Id");
        equipos.add("Nombre");
        equipos.add("Fecha Creacion");
        equipos.add("Estado");
        for (Object equipo : equipos) {

            modelo.addColumn(equipo);
        }
        jtProyecto.setModel(modelo);
    }

    private void llenarTabla() {
     //   Equipo equipoSeleccionado = (Equipo) jcbEquipo.getSelectedItem();

//        if (jrbNoInscriptas.isSelected()) {
//
//            List<Materia> materias = insData.obtenerMateriasNoCursadas(alumnoSeleccionado.getId_Alumno());
//            for (Materia m : materias) {
//
//                modelo.addRow(new Object[]{m.getId_Materia(), m.getNombre(), m.getAnio()});
//            }
//        } else {
//            List<Materia> materias = insData.obtenerMateriasCursadas(alumnoSeleccionado.getId_Alumno());
//            for (Materia m : materias) {
//
//                modelo.addRow(new Object[]{m.getId_Materia(), m.getNombre(), m.getAnio()});
//            }
//
//        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrEquipos;
    private javax.swing.JRadioButton jrProyectos;
    private javax.swing.JRadioButton jrTareas;
    private javax.swing.JTable jtProyecto;
    // End of variables declaration//GEN-END:variables
}
